CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    document_type   VARCHAR(50),
    document_number VARCHAR(50),
    phone           VARCHAR(20),
    
    email_encrypted VARCHAR(500) NOT NULL UNIQUE,
    username        VARCHAR(100) NOT NULL UNIQUE,
    
    password        VARCHAR(255) NOT NULL,
    profile_image_path VARCHAR(500),
    role            VARCHAR(50) NOT NULL,
    last_login      TIMESTAMP,
    status          VARCHAR(20) DEFAULT 'ACTIVE',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);